# This is a workflow for automatic deployment of Haskell application

name: deploy

# Controls when the workflow will run. Configure them for yourself
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#
env:
  proj-name: deploy-test

jobs:
  # On ubuntu
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.2'
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies
      - name: Build
        run: |
          cabal build ${{ env.proj-name }} # the next command doesn't work with -O2 unfortunately
          echo "path=$(cabal list-bin ${{ env.proj-name }})" >> $GITHUB_ENV
        
      - name: Deploy
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "${{ env.path }}"
          name: "Release-on-${{ runner.os }}" 
          folderId: ${{ secrets.folderId }} 
          overwrite: "true"
